monogatari.script({
    intro: [
        'The cold permeates my skin, my eyes are burning with sharp pains behind my eyes.',
        'j Ah.',
        'j It\'s already 8:35pm',
        'I\'m not a hard worker. I\'ve made peace with that. My life\'s purpose isn\'t to be some corporate slave. But I still find myself in the office, after everyone else.',
        'It\'s like theres something pulling me here... But I can\'t seem to slow down',
        'I guess working at WAKE isn\'t the worst job I could have. They pay for my studio apartment in the underworld. Heck, I even get a takeout allowance.',
        'Then again, I guess that\'s why I end up having to work here until almost 9 at night.',
        'WAKE... It\'s definetly not what I was expecting when I was applying for jobs.',
        'I thought it was a mattress store, all I\'d have to was some basic retail sales. Maybe carry heavy stuff once in a while.',
        '20, in that sharehouse, a shoebox excuse for a home. I was ready to dedicate myself to the art of sales to get out',
        'Instead I end up here. Great.',
        '...',
        'It\'s cold. The office is cold. My dinner is cold. And this job is cold.',
        'Wise And Knightly Enders (of your life). Huh. Not really pillow soft is it.',
        'And all these records...',
        '...',
        '...',
        'j Maybe I could just quit. It\'s been a bit of a passing thought for a while but...',
        'j I\'ve saved a lot of money working here. There\'s not much to spend it on.',
        'j My retirement fund could be worse...',
        'j ...And maybe I would rather be selling mattresses...',

        {
            Choice : {
                Yes : {
                    Text : 'Quit?',
                    Do: 'jump intro_freedom',
                },
                No : {
                    Text : 'Stay',
                    Do: 'jump quick_end',
                },
            },
        },
    ],
    intro_freedom: [
        'j I guess it\'s time then.',
        'It\'s so sudden, but it has been a long time coming.',
        'Reading the lists of the dead each day... making sure the right souls go to the right places... hiring new Reapers.',
        'Is that what I\'m made for?',
        'That\'s weirdly existential. Ugh. I need a cig',
        'Too bad smoking kills so many people. It\'s Reap or be Reaped.',
        '...',
        'I should go home now and prepare my things. Quitting a job here is so weirdly ceremonial.',
        'You\'d think a 2 week notice would be enough, but no. I have to host my own WAKE and find out if my career \'deserves\' to rest.',
        'If at least 2 of my coworkers don\'t think I\'m loveable enough to show up for my Wake, my career is still kicking.',
        'The only thing my career should be kicking is the bucket.',
        'I also need to commission my ceremonial coffin, a bouquet of flowers, and a cake for my wake...',
        'If I send in my notice now, and get everything ordered this week, I can get out ASAP.',
        'I\'m not in a rush, but I\'m not exactly NOT in a rush. I guess I\'ll be here a little longer to write my notice then.',
        'Sigh.',
        'jump baker_start',
    ],
});
